### ISSUE TITLE
185.90.152.0/23

### ISSUE THREAD

**Issue by mcdamm** [Commaster/IP-wall#1]
Hi Commaster

Can you please tell me the reason 185.90.152.0/23 is on the list? Please remove the whole range.
We are the owner of the range, probably you have it while it got re-annouced on 12th?
https://apps.db.ripe.net/db-web-ui/#/lookup?source=ripe&key=185.90.152.0%2F23AS6830&type=route

Thanks for fast removal

Best Regards
Michael

ITcom Pro AG
CTO

www.itcompro.ch

**Comment by Commaster** [comment]
Hi @mcdamm 

This range was added in early may 2018.
Sadly the logs only span 1 year, so I can't provide the intrusion logs.

Removing right away.

**Comment by Commaster** [comment]
I will follow up here if this range pops up again.
Cheers.

**Comment by mcdamm** [comment]
Hi @Commaster 

Thank you for fast response. In case of a range would pop up again, would you use abuse [at ] itcompro.com before adding again please?

Thanks & Best Regards
Michael

**Comment by Commaster** [comment]
@mcdamm do you happen to have a template for the e-mail? Cause many years ago I was tirelessly sending those abuse e-mails to all IP range owners and never got a response. So I gave up and started this.
